# Generated by Django 5.2 on 2025-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_rewardlog_scheduledreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_time_asked_reward",
            field=models.DateTimeField(null=True),
        ),
    ]
